// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBTest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PBTest_Corpus

typedef GPB_ENUM(PBTest_Corpus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PBTest_Corpus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PBTest_Corpus_Universal = 0,
  PBTest_Corpus_Web = 1,
  PBTest_Corpus_Images = 2,
  PBTest_Corpus_Local = 3,
  PBTest_Corpus_News = 4,
  PBTest_Corpus_Products = 5,
  PBTest_Corpus_Video = 6,
};

GPBEnumDescriptor *PBTest_Corpus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PBTest_Corpus_IsValidValue(int32_t value);

#pragma mark - PbtestRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PbtestRoot : GPBRootObject
@end

#pragma mark - PBTest

typedef GPB_ENUM(PBTest_FieldNumber) {
  PBTest_FieldNumber_Query = 1,
  PBTest_FieldNumber_PageNumber = 2,
  PBTest_FieldNumber_ResultPerPage = 3,
  PBTest_FieldNumber_Corpus = 4,
};

@interface PBTest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *query;

@property(nonatomic, readwrite) int32_t pageNumber;

@property(nonatomic, readwrite) int32_t resultPerPage;

@property(nonatomic, readwrite) PBTest_Corpus corpus;

@end

/**
 * Fetches the raw value of a @c PBTest's @c corpus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PBTest_Corpus_RawValue(PBTest *message);
/**
 * Sets the raw value of an @c PBTest's @c corpus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPBTest_Corpus_RawValue(PBTest *message, int32_t value);

#pragma mark - PBTest2

typedef GPB_ENUM(PBTest2_FieldNumber) {
  PBTest2_FieldNumber_RepArray = 4,
};

@interface PBTest2 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *repArray;
/** The number of items in @c repArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger repArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
